import { query } from "./db.server";
import { JOURNEY_VERSION } from "@/journey/config";
import { computeResult, resolvePath, type RawAnswer } from "@/journey/engine";
import { NODE_BY_CODE } from "@/journey/nodes";

type Session = { id: string; name: string; company: string; status: string; journey_version: string; started_at: string; completed_at: string | null };
export async function logEvent(sessionId: string | null, eventName: string, nodeCode?: string | null, metadata: Record<string, unknown> = {}) { await query("INSERT INTO analytics_events (session_id,event_name,node_code,metadata) VALUES ($1,$2,$3,$4::jsonb)", [sessionId,eventName,nodeCode ?? null,JSON.stringify(metadata)]); }
export async function createSession(name: string, company: string) { const { rows } = await query<{id:string}>("INSERT INTO journey_sessions (name,company,journey_version,status,current_node) VALUES ($1,$2,$3,'started','START-01') RETURNING id",[name,company,JOURNEY_VERSION]); const id=rows[0]!.id; await logEvent(id,"journey_started"); return id; }
export async function loadAnswers(sessionId: string): Promise<RawAnswer[]> { const { rows }=await query<{node_code:string;option_code:string}>("SELECT node_code,option_code FROM session_answers WHERE session_id=$1 AND active=true",[sessionId]); return rows.map((r)=>({nodeCode:r.node_code,optionCode:r.option_code})); }
export async function loadSession(sessionId:string) { const {rows}=await query<Session>("SELECT id,name,company,status,journey_version,started_at,completed_at FROM journey_sessions WHERE id=$1",[sessionId]); return rows[0] ?? null; }
export async function getState(sessionId:string) { const session=await loadSession(sessionId); if(!session)return null; const path=resolvePath(await loadAnswers(sessionId)); return {session:{id:session.id,name:session.name,company:session.company,status:session.status,journeyVersion:session.journey_version,startedAt:session.started_at,completedAt:session.completed_at},answers:path.validAnswers.map((a)=>({nodeCode:a.nodeCode,optionCode:a.optionCode})),path:path.path,currentNode:path.currentNode,completed:path.completed}; }
export async function saveAnswer(sessionId:string,nodeCode:string,optionCode:string) { const node=NODE_BY_CODE[nodeCode]; if(!node)throw new Error("Pergunta inválida."); if(!node.options.some((o)=>o.code===optionCode))throw new Error("Opção inválida."); await query("INSERT INTO session_answers (session_id,node_code,option_code,active,updated_at) VALUES ($1,$2,$3,true,now()) ON CONFLICT (session_id,node_code) DO UPDATE SET option_code=EXCLUDED.option_code,active=true,updated_at=now()",[sessionId,nodeCode,optionCode]); const path=resolvePath(await loadAnswers(sessionId)); if(path.invalidatedNodes.length)await query("UPDATE session_answers SET active=false,updated_at=now() WHERE session_id=$1 AND node_code=ANY($2::text[])",[sessionId,path.invalidatedNodes]); await query("UPDATE journey_sessions SET current_node=$2,status=$3,completed_at=CASE WHEN $4 THEN now() ELSE NULL END,last_activity_at=now() WHERE id=$1",[sessionId,path.currentNode,path.completed?"completed":"in_progress",path.completed]); await logEvent(sessionId,"question_answered",nodeCode,{optionCode}); return getState(sessionId); }
export async function buildResult(sessionId:string) { const session=await loadSession(sessionId);if(!session)return null;const answers=await loadAnswers(sessionId),path=resolvePath(answers),result=computeResult(answers);if(path.completed){await query("INSERT INTO result_snapshots (session_id,dimension_scores,service_scores,priorities,opportunities,structured_points,extra,uncertainty_rate,journey_version,engine_version) VALUES ($1,$2::jsonb,$3::jsonb,$4::jsonb,$5::jsonb,$6::jsonb,$7::jsonb,$8,$9,$10) ON CONFLICT (session_id) DO UPDATE SET dimension_scores=EXCLUDED.dimension_scores,service_scores=EXCLUDED.service_scores,priorities=EXCLUDED.priorities,opportunities=EXCLUDED.opportunities,structured_points=EXCLUDED.structured_points,extra=EXCLUDED.extra,uncertainty_rate=EXCLUDED.uncertainty_rate,journey_version=EXCLUDED.journey_version,engine_version=EXCLUDED.engine_version",[sessionId,JSON.stringify(result.dimensionScores),JSON.stringify(result.finalScores),JSON.stringify(result.priorities),JSON.stringify(result.opportunities),JSON.stringify(result.structuredPoints),JSON.stringify({diagnosticMode:result.diagnosticMode,diagnosticReasons:result.diagnosticReasons,investigationAreas:result.investigationAreas,ruleLogs:result.ruleLogs,commercialSummary:result.commercialSummary,rawServiceScores:result.serviceScores}),result.uncertaintyRate,session.journey_version,result.engineVersion]);if(session.status!=="completed")await query("UPDATE journey_sessions SET status='completed',completed_at=now() WHERE id=$1",[sessionId]);}const lead=await query("SELECT 1 FROM leads WHERE session_id=$1",[sessionId]);return {session:{id:session.id,name:session.name,company:session.company,journeyVersion:session.journey_version},completed:path.completed,hasLead:(lead.rowCount??0)>0,result}; }
export async function saveLead(input:{sessionId:string;email:string;whatsapp?:string;wantsContact:boolean;consent:boolean}) {await query("INSERT INTO leads (session_id,email,whatsapp,wants_contact,consent,submitted_at) VALUES ($1,$2,$3,$4,$5,now()) ON CONFLICT (session_id) DO UPDATE SET email=EXCLUDED.email,whatsapp=EXCLUDED.whatsapp,wants_contact=EXCLUDED.wants_contact,consent=EXCLUDED.consent,submitted_at=now()",[input.sessionId,input.email,input.whatsapp ?? null,input.wantsContact,input.consent]);await logEvent(input.sessionId,"lead_submitted");return true;}
export async function restart(sessionId:string){const session=await loadSession(sessionId);if(!session)throw new Error("Sessão não encontrada.");await query("UPDATE journey_sessions SET status='abandoned' WHERE id=$1",[sessionId]);const newId=await createSession(session.name,session.company);await logEvent(newId,"journey_restarted",null,{previousSession:sessionId});return newId;}
