/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as JornadaSessionIdRouteImport } from './routes/jornada/$sessionId'
import { Route as JornadaInicioRouteImport } from './routes/jornada/inicio'
import { Route as ResultadoSessionIdRouteImport } from './routes/resultado/$sessionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const JornadaSessionIdRoute = JornadaSessionIdRouteImport.update({
  id: '/jornada/$sessionId',
  path: '/jornada/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const JornadaInicioRoute = JornadaInicioRouteImport.update({
  id: '/jornada/inicio',
  path: '/jornada/inicio',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultadoSessionIdRoute = ResultadoSessionIdRouteImport.update({
  id: '/resultado/$sessionId',
  path: '/resultado/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/jornada/$sessionId': typeof JornadaSessionIdRoute
  '/jornada/inicio': typeof JornadaInicioRoute
  '/resultado/$sessionId': typeof ResultadoSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/jornada/$sessionId': typeof JornadaSessionIdRoute
  '/jornada/inicio': typeof JornadaInicioRoute
  '/resultado/$sessionId': typeof ResultadoSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/jornada/$sessionId': typeof JornadaSessionIdRoute
  '/jornada/inicio': typeof JornadaInicioRoute
  '/resultado/$sessionId': typeof ResultadoSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/jornada/$sessionId'
    | '/jornada/inicio'
    | '/resultado/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/jornada/$sessionId'
    | '/jornada/inicio'
    | '/resultado/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/jornada/$sessionId'
    | '/jornada/inicio'
    | '/resultado/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  JornadaSessionIdRoute: typeof JornadaSessionIdRoute
  JornadaInicioRoute: typeof JornadaInicioRoute
  ResultadoSessionIdRoute: typeof ResultadoSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/jornada/$sessionId': {
      id: '/jornada/$sessionId'
      path: '/jornada/$sessionId'
      fullPath: '/jornada/$sessionId'
      preLoaderRoute: typeof JornadaSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jornada/inicio': {
      id: '/jornada/inicio'
      path: '/jornada/inicio'
      fullPath: '/jornada/inicio'
      preLoaderRoute: typeof JornadaInicioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resultado/$sessionId': {
      id: '/resultado/$sessionId'
      path: '/resultado/$sessionId'
      fullPath: '/resultado/$sessionId'
      preLoaderRoute: typeof ResultadoSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  JornadaSessionIdRoute: JornadaSessionIdRoute,
  JornadaInicioRoute: JornadaInicioRoute,
  ResultadoSessionIdRoute: ResultadoSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
